services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        TAG: 3.12-slim
    hostname: app
    container_name: app
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN:?BOT_TOKEN_is_not_set}
      DB_USER: ${DB_USER:?DB_USER_is_not_set}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD_is_not_set}
      DB_HOST: ${DB_HOST:?DB_HOST_is_not_set}
      DB_PORT: ${DB_PORT:?DB_PORT_is_not_set}
      DB_DATABASE: ${DB_DATABASE:?DB_DATABASE_is_not_set}
